### ISSUE TITLE
Can't evaluate the pretrained model due to draccus parser.

### ISSUE THREAD

**Issue by Kimho666** [huggingface/lerobot#674]
![Image](https://github.com/user-attachments/assets/35fc3aee-00f4-4a99-80a3-4dc0b4589496)

I try example_2 to evaluate pretrained model but error occurs.

**Comment by aliberts** [comment]
We didn't push the pretrained models on the hub yet so it's pulling the old versions which don't work with this new config system. We'll update them very soon

**Comment by ylyhlh** [comment]
getting the same error.

**Comment by aliberts** [comment]
I've just pushed all pretrained policy on https://huggingface.co/lerobot (except `diffusion_pusht_keypoints`).
Example should be working now.

**Comment by Kimho666** [comment]
Yes, the models on hugging are updated 3 hours ago.

**Comment by Owenchan2001** [comment]
> I've just pushed all pretrained policy on https://huggingface.co/lerobot (except `diffusion_pusht_keypoints`). Example should be working now.

Even though I clone your policies (diffusion_pusht for example) and use the evaluation command provided by lerobot, I still got this kind of error.
raise ParsingError(f"Couldn't instantiate class {stringify_type(cls)} using the given arguments.") from e
draccus.utils.ParsingError: Couldn't instantiate class EvalPipelineConfig using the given arguments.

**Comment by ankile** [comment]
Hi, I'm still getting this issue when trying to load a diffusion policy that was created with the "official" training script: 

```
python lerobot/scripts/train.py \                                          
    --dataset.repo_id=ankile/franka-lift \
    --policy.type=diffusion \             
    --wandb.enable=true
```

When calling `policy = DiffusionPolicy.from_pretrained(pretrained_policy_path)` with the resulting saved models, I get

```
draccus.utils.ParsingError: Expected a dict with a 'type' key for <class 'lerobot.configs.policies.PreTrainedConfig'>, got {'n_obs_steps': 2,....
```

which seems strange to me because the repo is freshly installed as of a couple of days ago and using the standard training script and standard DP config.

Any hints?

**Comment by shantanuparab-tr** [comment]
Hey this is not the perfect solution.

```json
    "type": "act",
    "n_obs_steps": 1,
    "normalization_mapping": {
        "VISUAL": "MEAN_STD",
        "STATE": "MEAN_STD",
        "ACTION": "MEAN_STD"
    },
```

Adding a `type` key in your `config.json` file of the policy might solve it if it already does not exists. In your case type should be diffusion.

**Comment by TommyZihao** [comment]
> Hey this is not the perfect solution.
> 
>     "type": "act",
>     "n_obs_steps": 1,
>     "normalization_mapping": {
>         "VISUAL": "MEAN_STD",
>         "STATE": "MEAN_STD",
>         "ACTION": "MEAN_STD"
>     },
> Adding a `type` key in your `config.json` file of the policy might solve it if it already does not exists. In your case type should be diffusion.

still got the same error
